/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.ryandens.example.java-application-conventions")
    id("com.github.vlsi.jandex") version "1.90"
}

dependencies {
    implementation(enforcedPlatform("io.helidon:helidon-dependencies:4.0.2"))
    implementation("io.helidon.microprofile.bundles:helidon-microprofile")
    implementation("org.glassfish.jersey.media:jersey-media-json-binding")
    runtimeOnly("io.smallrye:jandex")
    runtimeOnly("jakarta.activation:jakarta.activation-api")
    testImplementation("io.helidon.microprofile.testing:helidon-microprofile-testing-junit5")
    testImplementation("org.assertj:assertj-core:3.11.1")
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

tasks.processResources {
    this.exclude("META-INF/beans.xml")
}

val copyBeans =
    tasks.create<Copy>("copyBeans") {
        dependsOn("processResources")
        from(layout.projectDirectory.dir("src/main/resources/META-INF/beans.xml"))
        into(layout.buildDirectory.dir("classes/java/main/META-INF"))
    }

tasks.compileJava {
    dependsOn(copyBeans)
}

application {
    // Define the main class for the application.
    mainClass.set("io.helidon.microprofile.cdi.Main")
}
