/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ryandens.example.utilities;

import com.ryandens.example.list.LinkedList;

public class StringUtils {
  public static String join(LinkedList source) {
    return JoinUtils.join(source);
  }

  public static LinkedList split(String source) {
    return SplitUtils.split(source);
  }
}
